// <auto-generated />
namespace Membership.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Correct_AuditFields_Max_Length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correct_AuditFields_Max_Length));
        
        string IMigrationMetadata.Id
        {
            get { return "201607121036379_Correct_AuditFields_Max_Length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
