// <auto-generated />
namespace Membership.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customer_child_entities_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customer_child_entities_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201604250930288_customer_child_entities_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
