// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Membership.Library.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customer_vendor_notes_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customer_vendor_notes_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201603171410289_customer_vendor_notes_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
