using Membership.Core;

namespace Membership.Library.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class Add_IsVirtualFlag_To_UserTable : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.User", "IsVirtual", c => c.Boolean(nullable: false));

            Sql($"UPDATE [dbo].[User] SET [IsVirtual] = 1 WHERE [Email] like '{MembershipConstant.AUTOGENERATED_USER_EMAIL_PREFIX}%'");
        }

        public override void Down()
        {
            DropColumn("dbo.User", "IsVirtual");
        }
    }
}
