// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Membership.Library.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class membership_init_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(membership_init_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201603031044154_membership_init_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
