// <auto-generated />
namespace Core.DynamicProperties.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_PrimaryKey_To_DynamicPropertyValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_PrimaryKey_To_DynamicPropertyValue));
        
        string IMigrationMetadata.Id
        {
            get { return "201608011700485_Add_PrimaryKey_To_DynamicPropertyValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
