// <auto-generated />
namespace Core.DynamicProperties.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_BaseEntity_To_DynamicProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_BaseEntity_To_DynamicProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201701140541323_Add_BaseEntity_To_DynamicProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
