namespace Membership.Core
{
    public static class MembershipConstant
    {
        public const char C_TOKEN_SEPARATOR = ':';
        public const int C_TOKEN_INDEX_ID = 0;
        public const int C_TOKEN_INDEX_PWD = 1;
        public const string C_PERSISTENT_USER_KEY = "PERSISTENT_USER";
        public const string C_PERSISTENT_PASSWORD_KEY = "PERSISTENT_PASSWORD";
        public const string C_USER_NAME_ADMIN = "Admin";
        public const string C_DEFAULT_TEMP_PASSWORD_KEY = "DEFAULT_TEMP_PASSWORD";

	    public const string SystemAdminUserName = "admin";

        public const string C_ROLE_CODE_COMPANYCLIENTSTAFF = "CCS";
        public const string C_ROLE_CODE_SYSADMIN = "SysAdmin";
        public const string C_ROLE_CODE_COMPANYADMIN = "CA";
        public const string C_ROLE_CODE_COMPANYSTAFF = "CS";
        public const string C_ROLE_CODE_COMPANYCLIENT = "CC";

        public const string ContactTypePhone = "Phone";

        public const string ContactTypeEmail = "Email";


        // TODO: Remove all usages of role name. Use only Code
        public const string C_ROLE_NAME_SYSADMIN = "SysAdmin";
        public const string C_ROLE_NAME_COMPANYADMIN = "CompanyAdmin";
        public const string C_ROLE_NAME_COMPANYSTAFF = "CompanyStaff";
        public const string C_ROLE_NAME_COMPANYCLIENT = "CompanyClient";
        public const string C_ROLE_NAME_COMPANYCLIENTSTAFF = "CompanyClientStaff";

        public const string C_ROLE_NAME_PRACTICEADMIN = "PracticeAdmin";
        public const string C_ROLE_CODE_PRACTICEADMIN = "PA";

        public const string C_ERROR_INVALID_USERNAME_OR_PWD = "Invalid username or password";
        public const string C_ERROR_VALIDATION_TOKEN_IS_EMPTY = "Validation token is empty";
        public const string C_ERROR_VALIDATION_TOKEN_PARSE_EXCEPTION = "Error while parse validation token";
        public const string C_ERROR_USER_NOT_EXIST = "User does not exist";
        public const string C_ERROR_INVALID_PWD = "Invalid user password";

        public const string C_ERROR_EMAIL_ALREADY_EXIST = "User with provided email already exists";

        public const string C_ERROR_PHONE_NUMBER_ALREADY_EXIST = "User with provided phone number already exists";

        public const string C_ERROR_USER_IS_NOT_AUTHORIZED = "User is not authorized";
        public const string C_ERROR_SITE_URL_NOT_FOUND = "Site url data not found in DB";

        public const string AUTOGENERATED_USER_EMAIL_PREFIX = "r____";

        public const string SysAdminPermission = "/sysadmin";
        public const string CancelImpersonationPermission = "/cancelImpersonation";
    }
}
