// <auto-generated />
namespace Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remove_UnsedFields_In_TemplateTable_So_Support_Modular : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remove_UnsedFields_In_TemplateTable_So_Support_Modular));
        
        string IMigrationMetadata.Id
        {
            get { return "201601120821010_Remove_UnsedFields_In_TemplateTable_So_Support_Modular"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
