//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoundComb.Testing.Prod {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespostaBase", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoundComb.Testing.Prod.RespostaMessageExternalIdentificador))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoundComb.Testing.Prod.RespostaSimpleMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoundComb.Testing.Prod.RespostaArrayOfTribunalExternal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoundComb.Testing.Prod.RespostaArrayOfUnidadeOrganicaExternal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoundComb.Testing.Prod.Respostastring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RoundComb.Testing.Prod.RespostaDocumento))]
    public partial class RespostaBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgErroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idErro {
            get {
                return this.idErroField;
            }
            set {
                if ((this.idErroField.Equals(value) != true)) {
                    this.idErroField = value;
                    this.RaisePropertyChanged("idErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msgErro {
            get {
                return this.msgErroField;
            }
            set {
                if ((object.ReferenceEquals(this.msgErroField, value) != true)) {
                    this.msgErroField = value;
                    this.RaisePropertyChanged("msgErro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespostaMessageExternalIdentificador", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class RespostaMessageExternalIdentificador : RoundComb.Testing.Prod.RespostaBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoundComb.Testing.Prod.MessageExternalIdentificador entidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoundComb.Testing.Prod.MessageExternalIdentificador entidade {
            get {
                return this.entidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.entidadeField, value) != true)) {
                    this.entidadeField = value;
                    this.RaisePropertyChanged("entidade");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespostaSimpleMessage", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class RespostaSimpleMessage : RoundComb.Testing.Prod.RespostaBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoundComb.Testing.Prod.SimpleMessage entidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoundComb.Testing.Prod.SimpleMessage entidade {
            get {
                return this.entidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.entidadeField, value) != true)) {
                    this.entidadeField = value;
                    this.RaisePropertyChanged("entidade");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespostaArrayOfTribunalExternal", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class RespostaArrayOfTribunalExternal : RoundComb.Testing.Prod.RespostaBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoundComb.Testing.Prod.TribunalExternal> entidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoundComb.Testing.Prod.TribunalExternal> entidade {
            get {
                return this.entidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.entidadeField, value) != true)) {
                    this.entidadeField = value;
                    this.RaisePropertyChanged("entidade");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespostaArrayOfUnidadeOrganicaExternal", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class RespostaArrayOfUnidadeOrganicaExternal : RoundComb.Testing.Prod.RespostaBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoundComb.Testing.Prod.UnidadeOrganicaExternal> entidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoundComb.Testing.Prod.UnidadeOrganicaExternal> entidade {
            get {
                return this.entidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.entidadeField, value) != true)) {
                    this.entidadeField = value;
                    this.RaisePropertyChanged("entidade");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respostastring", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class Respostastring : RoundComb.Testing.Prod.RespostaBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string entidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entidade {
            get {
                return this.entidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.entidadeField, value) != true)) {
                    this.entidadeField = value;
                    this.RaisePropertyChanged("entidade");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespostaDocumento", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class RespostaDocumento : RoundComb.Testing.Prod.RespostaBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoundComb.Testing.Prod.Documento entidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoundComb.Testing.Prod.Documento entidade {
            get {
                return this.entidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.entidadeField, value) != true)) {
                    this.entidadeField = value;
                    this.RaisePropertyChanged("entidade");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class Documento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string infoTecnicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string infoTecnica {
            get {
                return this.infoTecnicaField;
            }
            set {
                if ((object.ReferenceEquals(this.infoTecnicaField, value) != true)) {
                    this.infoTecnicaField = value;
                    this.RaisePropertyChanged("infoTecnica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageExternalIdentificador", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class MessageExternalIdentificador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idQueueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idQueue {
            get {
                return this.idQueueField;
            }
            set {
                if ((this.idQueueField.Equals(value) != true)) {
                    this.idQueueField = value;
                    this.RaisePropertyChanged("idQueue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msgId {
            get {
                return this.msgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.msgIdField, value) != true)) {
                    this.msgIdField = value;
                    this.RaisePropertyChanged("msgId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleMessage", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class SimpleMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TribunalExternal", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class TribunalExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidTribunalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTribunalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isAtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RoundComb.Testing.Prod.UnidadeOrganicaExternal> lstUnidadesOrganicasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tribunalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guidTribunal {
            get {
                return this.guidTribunalField;
            }
            set {
                if ((object.ReferenceEquals(this.guidTribunalField, value) != true)) {
                    this.guidTribunalField = value;
                    this.RaisePropertyChanged("guidTribunal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTribunal {
            get {
                return this.idTribunalField;
            }
            set {
                if ((this.idTribunalField.Equals(value) != true)) {
                    this.idTribunalField = value;
                    this.RaisePropertyChanged("idTribunal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isAtivo {
            get {
                return this.isAtivoField;
            }
            set {
                if ((this.isAtivoField.Equals(value) != true)) {
                    this.isAtivoField = value;
                    this.RaisePropertyChanged("isAtivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RoundComb.Testing.Prod.UnidadeOrganicaExternal> lstUnidadesOrganicas {
            get {
                return this.lstUnidadesOrganicasField;
            }
            set {
                if ((object.ReferenceEquals(this.lstUnidadesOrganicasField, value) != true)) {
                    this.lstUnidadesOrganicasField = value;
                    this.RaisePropertyChanged("lstUnidadesOrganicas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nif {
            get {
                return this.nifField;
            }
            set {
                if ((object.ReferenceEquals(this.nifField, value) != true)) {
                    this.nifField = value;
                    this.RaisePropertyChanged("nif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                if ((this.timeStampField.Equals(value) != true)) {
                    this.timeStampField = value;
                    this.RaisePropertyChanged("timeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tribunal {
            get {
                return this.tribunalField;
            }
            set {
                if ((object.ReferenceEquals(this.tribunalField, value) != true)) {
                    this.tribunalField = value;
                    this.RaisePropertyChanged("tribunal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnidadeOrganicaExternal", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class UnidadeOrganicaExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cPostal3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cPostal4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidTribunalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidUnidadeOrganicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTribunalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUnidadeOrganicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isAtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isUnidadeCentralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string localidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moradaComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tribunalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidadeOrganicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cPostal3 {
            get {
                return this.cPostal3Field;
            }
            set {
                if ((this.cPostal3Field.Equals(value) != true)) {
                    this.cPostal3Field = value;
                    this.RaisePropertyChanged("cPostal3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cPostal4 {
            get {
                return this.cPostal4Field;
            }
            set {
                if ((this.cPostal4Field.Equals(value) != true)) {
                    this.cPostal4Field = value;
                    this.RaisePropertyChanged("cPostal4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eMail {
            get {
                return this.eMailField;
            }
            set {
                if ((object.ReferenceEquals(this.eMailField, value) != true)) {
                    this.eMailField = value;
                    this.RaisePropertyChanged("eMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                if ((object.ReferenceEquals(this.faxField, value) != true)) {
                    this.faxField = value;
                    this.RaisePropertyChanged("fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guidTribunal {
            get {
                return this.guidTribunalField;
            }
            set {
                if ((object.ReferenceEquals(this.guidTribunalField, value) != true)) {
                    this.guidTribunalField = value;
                    this.RaisePropertyChanged("guidTribunal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guidUnidadeOrganica {
            get {
                return this.guidUnidadeOrganicaField;
            }
            set {
                if ((object.ReferenceEquals(this.guidUnidadeOrganicaField, value) != true)) {
                    this.guidUnidadeOrganicaField = value;
                    this.RaisePropertyChanged("guidUnidadeOrganica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTribunal {
            get {
                return this.idTribunalField;
            }
            set {
                if ((this.idTribunalField.Equals(value) != true)) {
                    this.idTribunalField = value;
                    this.RaisePropertyChanged("idTribunal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUnidadeOrganica {
            get {
                return this.idUnidadeOrganicaField;
            }
            set {
                if ((this.idUnidadeOrganicaField.Equals(value) != true)) {
                    this.idUnidadeOrganicaField = value;
                    this.RaisePropertyChanged("idUnidadeOrganica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isAtivo {
            get {
                return this.isAtivoField;
            }
            set {
                if ((this.isAtivoField.Equals(value) != true)) {
                    this.isAtivoField = value;
                    this.RaisePropertyChanged("isAtivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isUnidadeCentral {
            get {
                return this.isUnidadeCentralField;
            }
            set {
                if ((this.isUnidadeCentralField.Equals(value) != true)) {
                    this.isUnidadeCentralField = value;
                    this.RaisePropertyChanged("isUnidadeCentral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localidade {
            get {
                return this.localidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.localidadeField, value) != true)) {
                    this.localidadeField = value;
                    this.RaisePropertyChanged("localidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string morada {
            get {
                return this.moradaField;
            }
            set {
                if ((object.ReferenceEquals(this.moradaField, value) != true)) {
                    this.moradaField = value;
                    this.RaisePropertyChanged("morada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moradaComplemento {
            get {
                return this.moradaComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.moradaComplementoField, value) != true)) {
                    this.moradaComplementoField = value;
                    this.RaisePropertyChanged("moradaComplemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneField, value) != true)) {
                    this.telefoneField = value;
                    this.RaisePropertyChanged("telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                if ((this.timeStampField.Equals(value) != true)) {
                    this.timeStampField = value;
                    this.RaisePropertyChanged("timeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tribunal {
            get {
                return this.tribunalField;
            }
            set {
                if ((object.ReferenceEquals(this.tribunalField, value) != true)) {
                    this.tribunalField = value;
                    this.RaisePropertyChanged("tribunal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unidadeOrganica {
            get {
                return this.unidadeOrganicaField;
            }
            set {
                if ((object.ReferenceEquals(this.unidadeOrganicaField, value) != true)) {
                    this.unidadeOrganicaField = value;
                    this.RaisePropertyChanged("unidadeOrganica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageExternal", Namespace="http://schemas.datacontract.org/2004/07/CitiusNext.External.Interoperability.Data" +
        "Contracts")]
    [System.SerializableAttribute()]
    public partial class MessageExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string msgIdField;
        
        private System.DateTime msgDateField;
        
        private string msgSenderIdField;
        
        private string msgReceiverIdField;
        
        private int msgTypeIdField;
        
        private string msgTypeField;
        
        private string msgExternalRefField;
        
        private string msgBodyField;
        
        private string msgUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string msgId {
            get {
                return this.msgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.msgIdField, value) != true)) {
                    this.msgIdField = value;
                    this.RaisePropertyChanged("msgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime msgDate {
            get {
                return this.msgDateField;
            }
            set {
                if ((this.msgDateField.Equals(value) != true)) {
                    this.msgDateField = value;
                    this.RaisePropertyChanged("msgDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string msgSenderId {
            get {
                return this.msgSenderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.msgSenderIdField, value) != true)) {
                    this.msgSenderIdField = value;
                    this.RaisePropertyChanged("msgSenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string msgReceiverId {
            get {
                return this.msgReceiverIdField;
            }
            set {
                if ((object.ReferenceEquals(this.msgReceiverIdField, value) != true)) {
                    this.msgReceiverIdField = value;
                    this.RaisePropertyChanged("msgReceiverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int msgTypeId {
            get {
                return this.msgTypeIdField;
            }
            set {
                if ((this.msgTypeIdField.Equals(value) != true)) {
                    this.msgTypeIdField = value;
                    this.RaisePropertyChanged("msgTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string msgType {
            get {
                return this.msgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.msgTypeField, value) != true)) {
                    this.msgTypeField = value;
                    this.RaisePropertyChanged("msgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string msgExternalRef {
            get {
                return this.msgExternalRefField;
            }
            set {
                if ((object.ReferenceEquals(this.msgExternalRefField, value) != true)) {
                    this.msgExternalRefField = value;
                    this.RaisePropertyChanged("msgExternalRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string msgBody {
            get {
                return this.msgBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.msgBodyField, value) != true)) {
                    this.msgBodyField = value;
                    this.RaisePropertyChanged("msgBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string msgUser {
            get {
                return this.msgUserField;
            }
            set {
                if ((object.ReferenceEquals(this.msgUserField, value) != true)) {
                    this.msgUserField = value;
                    this.RaisePropertyChanged("msgUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Prod.ISoapApi")]
    public interface ISoapApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getDocumento", ReplyAction="http://tempuri.org/ISoapApi/getDocumentoResponse")]
        RoundComb.Testing.Prod.RespostaDocumento getDocumento(string idMsgEntity, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getMessageValidation", ReplyAction="http://tempuri.org/ISoapApi/getMessageValidationResponse")]
        RoundComb.Testing.Prod.RespostaMessageExternalIdentificador getMessageValidation(string idMsgEntity, RoundComb.Testing.Prod.MessageExternal msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/setMessageSubmit", ReplyAction="http://tempuri.org/ISoapApi/setMessageSubmitResponse")]
        RoundComb.Testing.Prod.RespostaMessageExternalIdentificador setMessageSubmit(string idMsgEntity, RoundComb.Testing.Prod.MessageExternal msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/isAlive", ReplyAction="http://tempuri.org/ISoapApi/isAliveResponse")]
        RoundComb.Testing.Prod.RespostaSimpleMessage isAlive(string idMsgEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getMessageCompleteXsd", ReplyAction="http://tempuri.org/ISoapApi/getMessageCompleteXsdResponse")]
        RoundComb.Testing.Prod.RespostaSimpleMessage getMessageCompleteXsd(string idMsgEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getMsgBodyXsd", ReplyAction="http://tempuri.org/ISoapApi/getMsgBodyXsdResponse")]
        RoundComb.Testing.Prod.RespostaSimpleMessage getMsgBodyXsd(string idMsgEntity, int msgTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getMsgBodySimplifiedXsd", ReplyAction="http://tempuri.org/ISoapApi/getMsgBodySimplifiedXsdResponse")]
        RoundComb.Testing.Prod.RespostaSimpleMessage getMsgBodySimplifiedXsd(string idMsgEntity, int msgTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getTribunaisList", ReplyAction="http://tempuri.org/ISoapApi/getTribunaisListResponse")]
        RoundComb.Testing.Prod.RespostaArrayOfTribunalExternal getTribunaisList(string idMsgEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getUnidadesOrganicasListByIdTribunal", ReplyAction="http://tempuri.org/ISoapApi/getUnidadesOrganicasListByIdTribunalResponse")]
        RoundComb.Testing.Prod.RespostaArrayOfUnidadeOrganicaExternal getUnidadesOrganicasListByIdTribunal(string idMsgEntity, int idTribunal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getEstadoDistribuicaoProcesso", ReplyAction="http://tempuri.org/ISoapApi/getEstadoDistribuicaoProcessoResponse")]
        RoundComb.Testing.Prod.Respostastring getEstadoDistribuicaoProcesso(string idMsgEntity, string processo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getEstadoComunicacaoProcesso", ReplyAction="http://tempuri.org/ISoapApi/getEstadoComunicacaoProcessoResponse")]
        RoundComb.Testing.Prod.Respostastring getEstadoComunicacaoProcesso(string idMsgEntity, string idMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoapApi/getLocalizarProcesso", ReplyAction="http://tempuri.org/ISoapApi/getLocalizarProcessoResponse")]
        RoundComb.Testing.Prod.Respostastring getLocalizarProcesso(string idMsgEntity, string processo, string guidprocesso, string nifInterv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoapApiChannel : RoundComb.Testing.Prod.ISoapApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapApiClient : System.ServiceModel.ClientBase<RoundComb.Testing.Prod.ISoapApi>, RoundComb.Testing.Prod.ISoapApi {
        
        public SoapApiClient() {
        }
        
        public SoapApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RoundComb.Testing.Prod.RespostaDocumento getDocumento(string idMsgEntity, string fileName) {
            return base.Channel.getDocumento(idMsgEntity, fileName);
        }
        
        public RoundComb.Testing.Prod.RespostaMessageExternalIdentificador getMessageValidation(string idMsgEntity, RoundComb.Testing.Prod.MessageExternal msg) {
            return base.Channel.getMessageValidation(idMsgEntity, msg);
        }
        
        public RoundComb.Testing.Prod.RespostaMessageExternalIdentificador setMessageSubmit(string idMsgEntity, RoundComb.Testing.Prod.MessageExternal msg) {
            return base.Channel.setMessageSubmit(idMsgEntity, msg);
        }
        
        public RoundComb.Testing.Prod.RespostaSimpleMessage isAlive(string idMsgEntity) {
            return base.Channel.isAlive(idMsgEntity);
        }
        
        public RoundComb.Testing.Prod.RespostaSimpleMessage getMessageCompleteXsd(string idMsgEntity) {
            return base.Channel.getMessageCompleteXsd(idMsgEntity);
        }
        
        public RoundComb.Testing.Prod.RespostaSimpleMessage getMsgBodyXsd(string idMsgEntity, int msgTypeId) {
            return base.Channel.getMsgBodyXsd(idMsgEntity, msgTypeId);
        }
        
        public RoundComb.Testing.Prod.RespostaSimpleMessage getMsgBodySimplifiedXsd(string idMsgEntity, int msgTypeId) {
            return base.Channel.getMsgBodySimplifiedXsd(idMsgEntity, msgTypeId);
        }
        
        public RoundComb.Testing.Prod.RespostaArrayOfTribunalExternal getTribunaisList(string idMsgEntity) {
            return base.Channel.getTribunaisList(idMsgEntity);
        }
        
        public RoundComb.Testing.Prod.RespostaArrayOfUnidadeOrganicaExternal getUnidadesOrganicasListByIdTribunal(string idMsgEntity, int idTribunal) {
            return base.Channel.getUnidadesOrganicasListByIdTribunal(idMsgEntity, idTribunal);
        }
        
        public RoundComb.Testing.Prod.Respostastring getEstadoDistribuicaoProcesso(string idMsgEntity, string processo) {
            return base.Channel.getEstadoDistribuicaoProcesso(idMsgEntity, processo);
        }
        
        public RoundComb.Testing.Prod.Respostastring getEstadoComunicacaoProcesso(string idMsgEntity, string idMsg) {
            return base.Channel.getEstadoComunicacaoProcesso(idMsgEntity, idMsg);
        }
        
        public RoundComb.Testing.Prod.Respostastring getLocalizarProcesso(string idMsgEntity, string processo, string guidprocesso, string nifInterv) {
            return base.Channel.getLocalizarProcesso(idMsgEntity, processo, guidprocesso, nifInterv);
        }
    }
}
