// <auto-generated />
namespace CustomForm.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_InitialData_CustomForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_InitialData_CustomForm));
        
        string IMigrationMetadata.Id
        {
            get { return "201605161440521_Add_InitialData_CustomForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
