// <auto-generated />
namespace CustomForm.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_UploadedPaths_Support_For_Dynamic_Upload_Control : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_UploadedPaths_Support_For_Dynamic_Upload_Control));
        
        string IMigrationMetadata.Id
        {
            get { return "201607111517598_Added_UploadedPaths_Support_For_Dynamic_Upload_Control"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
